apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: druids.druid.splunk.com
spec:
  group: druid.splunk.com
  names:
    kind: Druid
    listKind: DruidList
    plural: druids
    singular: druid
  scope: Namespaced
  version: v1alpha1
