kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: cja-prod
  name: druid-app-operator
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]

- apiGroups: [""] # "" indicates the core API group
  resources: ["events"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]

- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]

- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]

- apiGroups: ["druid.splunk.com"]
  resources: ["*"]
  verbs: ["*"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-druid-app-operator
  namespace: cja-prod
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: druid-app-operator
  apiGroup: rbac.authorization.k8s.io
